"""core operational and dashboard schema

Revision ID: 0001_core
Revises:
"""

import sqlalchemy as sa

from alembic import op

revision = "0001_core"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("es_propia", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
        sa.UniqueConstraint("nombre", name=op.f("uq_institutions_nombre")),
    )
    op.create_index(
        "uq_institutions_own",
        "institutions",
        ["es_propia"],
        unique=True,
        postgresql_where=sa.text("es_propia = true"),
    )
    op.create_table(
        "provincias",
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("poblacion", sa.Integer(), nullable=True),
        sa.Column("superficie_km2", sa.Float(), nullable=True),
        sa.Column("fuente", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("poblacion >= 0", name=op.f("ck_provincias_population")),
        sa.CheckConstraint("superficie_km2 > 0", name=op.f("ck_provincias_area")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provincias")),
        sa.UniqueConstraint("nombre", name=op.f("uq_provincias_nombre")),
    )
    op.create_index(op.f("ix_provincias_region"), "provincias", ["region"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "OPERATOR", "ANALYST", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_normalized_email")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("accion", sa.String(length=60), nullable=False),
        sa.Column("entidad", sa.String(length=80), nullable=False),
        sa.Column("entidad_id", sa.Uuid(), nullable=True),
        sa.Column("cambios", sa.JSON(), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entidad"), "audit_logs", ["entidad"], unique=False)
    op.create_index(op.f("ix_audit_logs_fecha"), "audit_logs", ["fecha"], unique=False)
    op.create_table(
        "candidate_locations",
        sa.Column("codigo", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("municipio", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.Enum("ATM", "SUCURSAL", name="location_type"), nullable=False),
        sa.Column("latitud", sa.Float(), nullable=False),
        sa.Column("longitud", sa.Float(), nullable=False),
        sa.Column("potencial_mercado", sa.Float(), nullable=False),
        sa.Column("densidad_poblacional", sa.Float(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "PROPUESTA", "EN_EVALUACION", "APROBADA", "DESCARTADA", name="candidate_status"
            ),
            nullable=False,
        ),
        sa.Column("fuente", sa.String(length=255), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180",
            name=op.f("ck_candidate_locations_coordinates"),
        ),
        sa.CheckConstraint(
            "potencial_mercado BETWEEN 0 AND 100 AND densidad_poblacional >= 0",
            name=op.f("ck_candidate_locations_score_density"),
        ),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincias.nombre"],
            name=op.f("fk_candidate_locations_provincia_provincias"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_locations")),
        sa.UniqueConstraint("codigo", name=op.f("uq_candidate_locations_codigo")),
    )
    op.create_index(
        op.f("ix_candidate_locations_potencial_mercado"),
        "candidate_locations",
        ["potencial_mercado"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_locations_provincia"), "candidate_locations", ["provincia"], unique=False
    )
    op.create_table(
        "competitor_locations",
        sa.Column("institucion_id", sa.Uuid(), nullable=False),
        sa.Column("codigo", sa.String(length=80), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.Enum("ATM", "SUCURSAL", name="location_type"), nullable=False),
        sa.Column("latitud", sa.Float(), nullable=False),
        sa.Column("longitud", sa.Float(), nullable=False),
        sa.Column("fuente", sa.String(length=255), nullable=False),
        sa.Column("fecha_verificacion", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180",
            name=op.f("ck_competitor_locations_coordinates"),
        ),
        sa.ForeignKeyConstraint(
            ["institucion_id"],
            ["institutions.id"],
            name=op.f("fk_competitor_locations_institucion_id_institutions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincias.nombre"],
            name=op.f("fk_competitor_locations_provincia_provincias"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitor_locations")),
        sa.UniqueConstraint(
            "institucion_id", "codigo", name=op.f("uq_competitor_locations_institucion_id")
        ),
    )
    op.create_index(
        op.f("ix_competitor_locations_institucion_id"),
        "competitor_locations",
        ["institucion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competitor_locations_provincia"),
        "competitor_locations",
        ["provincia"],
        unique=False,
    )
    op.create_table(
        "market_snapshots",
        sa.Column("institucion_id", sa.Uuid(), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("total_atms", sa.Integer(), nullable=False),
        sa.Column("total_sucursales", sa.Integer(), nullable=False),
        sa.Column("depositos", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("prestamos", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("transacciones", sa.Integer(), nullable=False),
        sa.Column("utilizacion_pct", sa.Float(), nullable=True),
        sa.Column("fuente", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "total_atms >= 0 AND total_sucursales >= 0 AND transacciones >= 0 AND depositos >= 0 AND prestamos >= 0",
            name=op.f("ck_market_snapshots_positive_metrics"),
        ),
        sa.CheckConstraint(
            "utilizacion_pct BETWEEN 0 AND 100", name=op.f("ck_market_snapshots_utilization")
        ),
        sa.ForeignKeyConstraint(
            ["institucion_id"],
            ["institutions.id"],
            name=op.f("fk_market_snapshots_institucion_id_institutions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincias.nombre"],
            name=op.f("fk_market_snapshots_provincia_provincias"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
        sa.UniqueConstraint(
            "institucion_id", "provincia", "fecha", name=op.f("uq_market_snapshots_institucion_id")
        ),
    )
    op.create_index(op.f("ix_market_snapshots_fecha"), "market_snapshots", ["fecha"], unique=False)
    op.create_index(
        op.f("ix_market_snapshots_institucion_id"),
        "market_snapshots",
        ["institucion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_snapshots_provincia"), "market_snapshots", ["provincia"], unique=False
    )
    op.create_table(
        "sucursales",
        sa.Column("codigo", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("municipio", sa.String(length=100), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=False),
        sa.Column("latitud", sa.Float(), nullable=False),
        sa.Column("longitud", sa.Float(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("OPERATIVA", "MANTENIMIENTO", "CERRADA", name="branch_status"),
            nullable=False,
        ),
        sa.Column("total_cajeros_humanos", sa.Integer(), nullable=False),
        sa.Column("sla_objetivo_segundos", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180",
            name=op.f("ck_sucursales_coordinates"),
        ),
        sa.CheckConstraint(
            "total_cajeros_humanos >= 0 AND sla_objetivo_segundos > 0",
            name=op.f("ck_sucursales_capacity_sla"),
        ),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincias.nombre"],
            name=op.f("fk_sucursales_provincia_provincias"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sucursales")),
        sa.UniqueConstraint("codigo", name=op.f("uq_sucursales_codigo")),
    )
    op.create_index(op.f("ix_sucursales_provincia"), "sucursales", ["provincia"], unique=False)
    op.create_table(
        "atms",
        sa.Column("codigo_unico", sa.String(length=40), nullable=False),
        sa.Column("sucursal_id", sa.Uuid(), nullable=True),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("municipio", sa.String(length=100), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=False),
        sa.Column("tipo", sa.Enum("DISPENSADOR", "CDM_DEPOSITO", name="atm_type"), nullable=False),
        sa.Column("nivel_efectivo_pct", sa.Float(), nullable=False),
        sa.Column("capacidad_efectivo", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "OPERATIVO",
                "BAJO_EFECTIVO",
                "FUERA_DE_SERVICIO",
                "MANTENIMIENTO",
                name="atm_status",
            ),
            nullable=False,
        ),
        sa.Column("latitud", sa.Float(), nullable=False),
        sa.Column("longitud", sa.Float(), nullable=False),
        sa.Column("ultima_comunicacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_mantenimiento", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacidad_efectivo > 0", name=op.f("ck_atms_cash_capacity")),
        sa.CheckConstraint(
            "latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180",
            name=op.f("ck_atms_coordinates"),
        ),
        sa.CheckConstraint(
            "nivel_efectivo_pct BETWEEN 0 AND 100", name=op.f("ck_atms_cash_percentage")
        ),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincias.nombre"],
            name=op.f("fk_atms_provincia_provincias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_atms_sucursal_id_sucursales"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_atms")),
    )
    op.create_index(op.f("ix_atms_codigo_unico"), "atms", ["codigo_unico"], unique=True)
    op.create_index(op.f("ix_atms_estado"), "atms", ["estado"], unique=False)
    op.create_index(op.f("ix_atms_provincia"), "atms", ["provincia"], unique=False)
    op.create_index(op.f("ix_atms_sucursal_id"), "atms", ["sucursal_id"], unique=False)
    op.create_table(
        "branch_financials",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("depositos", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("prestamos", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "depositos >= 0 AND prestamos >= 0", name=op.f("ck_branch_financials_balances")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_branch_financials_sucursal_id_sucursales"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branch_financials")),
        sa.UniqueConstraint("sucursal_id", "fecha", name=op.f("uq_branch_financials_sucursal_id")),
    )
    op.create_index(
        op.f("ix_branch_financials_fecha"), "branch_financials", ["fecha"], unique=False
    )
    op.create_index(
        op.f("ix_branch_financials_sucursal_id"), "branch_financials", ["sucursal_id"], unique=False
    )
    op.create_table(
        "branch_readings",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("hora", sa.DateTime(timezone=True), nullable=False),
        sa.Column("visitantes", sa.Integer(), nullable=False),
        sa.Column("clientes_atendidos", sa.Integer(), nullable=False),
        sa.Column("clientes_dentro_sla", sa.Integer(), nullable=False),
        sa.Column("espera_total_segundos", sa.Integer(), nullable=False),
        sa.Column("cajeros_disponibles", sa.Integer(), nullable=False),
        sa.Column("cola_actual", sa.Integer(), nullable=False),
        sa.Column("segundos_cajero_disponibles", sa.Integer(), nullable=False),
        sa.Column("segundos_cajero_ocupados", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "clientes_atendidos > 0 OR espera_total_segundos = 0",
            name=op.f("ck_branch_readings_wait_denominator"),
        ),
        sa.CheckConstraint(
            "espera_total_segundos >= 0 AND cajeros_disponibles >= 0 AND cola_actual >= 0",
            name=op.f("ck_branch_readings_queue"),
        ),
        sa.CheckConstraint(
            "segundos_cajero_disponibles >= 0 AND segundos_cajero_ocupados BETWEEN 0 AND segundos_cajero_disponibles",
            name=op.f("ck_branch_readings_tellers"),
        ),
        sa.CheckConstraint(
            "visitantes >= 0 AND clientes_atendidos >= 0 AND clientes_dentro_sla BETWEEN 0 AND clientes_atendidos",
            name=op.f("ck_branch_readings_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_branch_readings_sucursal_id_sucursales"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branch_readings")),
        sa.UniqueConstraint("sucursal_id", "hora", name=op.f("uq_branch_readings_sucursal_id")),
    )
    op.create_index(op.f("ix_branch_readings_hora"), "branch_readings", ["hora"], unique=False)
    op.create_index(
        op.f("ix_branch_readings_sucursal_id"), "branch_readings", ["sucursal_id"], unique=False
    )
    op.create_table(
        "atm_readings",
        sa.Column("atm_id", sa.Uuid(), nullable=False),
        sa.Column("hora", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transacciones", sa.Integer(), nullable=False),
        sa.Column("transacciones_exitosas", sa.Integer(), nullable=False),
        sa.Column("monto_retirado", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("nivel_efectivo_pct", sa.Float(), nullable=False),
        sa.Column("segundos_observados", sa.Integer(), nullable=False),
        sa.Column("segundos_disponible", sa.Integer(), nullable=False),
        sa.Column("segundos_utilizado", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "nivel_efectivo_pct BETWEEN 0 AND 100", name=op.f("ck_atm_readings_cash")
        ),
        sa.CheckConstraint(
            "segundos_observados BETWEEN 1 AND 3600 AND segundos_disponible BETWEEN 0 AND segundos_observados AND segundos_utilizado BETWEEN 0 AND segundos_disponible",
            name=op.f("ck_atm_readings_time_counters"),
        ),
        sa.CheckConstraint(
            "transacciones >= 0 AND transacciones_exitosas BETWEEN 0 AND transacciones AND monto_retirado >= 0",
            name=op.f("ck_atm_readings_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["atm_id"], ["atms.id"], name=op.f("fk_atm_readings_atm_id_atms"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_atm_readings")),
        sa.UniqueConstraint("atm_id", "hora", name=op.f("uq_atm_readings_atm_id")),
    )
    op.create_index(op.f("ix_atm_readings_atm_id"), "atm_readings", ["atm_id"], unique=False)
    op.create_index(op.f("ix_atm_readings_hora"), "atm_readings", ["hora"], unique=False)
    op.create_table(
        "incidencias",
        sa.Column("atm_id", sa.Uuid(), nullable=True),
        sa.Column("sucursal_id", sa.Uuid(), nullable=True),
        sa.Column("tipo_falla", sa.String(length=150), nullable=False),
        sa.Column(
            "severidad",
            sa.Enum("BAJA", "MEDIA", "ALTA", "CRITICA", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum("ABIERTA", "EN_PROCESO", "RESUELTA", "CANCELADA", name="incident_status"),
            nullable=False,
        ),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("resolucion", sa.Text(), nullable=True),
        sa.Column("creado_por_id", sa.Uuid(), nullable=False),
        sa.Column("asignado_a_id", sa.Uuid(), nullable=True),
        sa.Column("fecha_apertura", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_cierre", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(estado IN ('ABIERTA','EN_PROCESO') AND fecha_cierre IS NULL) OR (estado IN ('RESUELTA','CANCELADA') AND fecha_cierre IS NOT NULL AND resolucion IS NOT NULL)",
            name=op.f("ck_incidencias_closure_state"),
        ),
        sa.CheckConstraint(
            "(atm_id IS NOT NULL AND sucursal_id IS NULL) OR (atm_id IS NULL AND sucursal_id IS NOT NULL)",
            name=op.f("ck_incidencias_exactly_one_target"),
        ),
        sa.CheckConstraint(
            "fecha_cierre >= fecha_apertura", name=op.f("ck_incidencias_closure_time")
        ),
        sa.ForeignKeyConstraint(
            ["asignado_a_id"],
            ["users.id"],
            name=op.f("fk_incidencias_asignado_a_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["atm_id"], ["atms.id"], name=op.f("fk_incidencias_atm_id_atms"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["creado_por_id"],
            ["users.id"],
            name=op.f("fk_incidencias_creado_por_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_incidencias_sucursal_id_sucursales"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidencias")),
    )
    op.create_index(op.f("ix_incidencias_atm_id"), "incidencias", ["atm_id"], unique=False)
    op.create_index(op.f("ix_incidencias_estado"), "incidencias", ["estado"], unique=False)
    op.create_index(
        op.f("ix_incidencias_fecha_apertura"), "incidencias", ["fecha_apertura"], unique=False
    )
    op.create_index(
        op.f("ix_incidencias_sucursal_id"), "incidencias", ["sucursal_id"], unique=False
    )
    op.create_table(
        "logistica_recargas",
        sa.Column("atm_id", sa.Uuid(), nullable=False),
        sa.Column("monto_solicitado", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("monto_entregado", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("transportadora", sa.String(length=150), nullable=False),
        sa.Column("referencia", sa.String(length=80), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PROGRAMADA", "EN_TRANSITO", "COMPLETADA", "CANCELADA", name="refill_status"),
            nullable=False,
        ),
        sa.Column("fecha_programada", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_ejecucion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("creado_por_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(estado = 'COMPLETADA' AND fecha_ejecucion IS NOT NULL AND monto_entregado IS NOT NULL) OR (estado != 'COMPLETADA' AND fecha_ejecucion IS NULL AND monto_entregado IS NULL)",
            name=op.f("ck_logistica_recargas_execution_state"),
        ),
        sa.CheckConstraint(
            "monto_solicitado > 0 AND (monto_entregado IS NULL OR monto_entregado > 0)",
            name=op.f("ck_logistica_recargas_positive_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["atm_id"],
            ["atms.id"],
            name=op.f("fk_logistica_recargas_atm_id_atms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creado_por_id"],
            ["users.id"],
            name=op.f("fk_logistica_recargas_creado_por_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logistica_recargas")),
        sa.UniqueConstraint("referencia", name=op.f("uq_logistica_recargas_referencia")),
    )
    op.create_index(
        op.f("ix_logistica_recargas_atm_id"), "logistica_recargas", ["atm_id"], unique=False
    )
    op.create_index(
        op.f("ix_logistica_recargas_estado"), "logistica_recargas", ["estado"], unique=False
    )
    op.create_index(
        op.f("ix_logistica_recargas_fecha_programada"),
        "logistica_recargas",
        ["fecha_programada"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logistica_recargas_fecha_programada"), table_name="logistica_recargas")
    op.drop_index(op.f("ix_logistica_recargas_estado"), table_name="logistica_recargas")
    op.drop_index(op.f("ix_logistica_recargas_atm_id"), table_name="logistica_recargas")
    op.drop_table("logistica_recargas")
    op.drop_index(op.f("ix_incidencias_sucursal_id"), table_name="incidencias")
    op.drop_index(op.f("ix_incidencias_fecha_apertura"), table_name="incidencias")
    op.drop_index(op.f("ix_incidencias_estado"), table_name="incidencias")
    op.drop_index(op.f("ix_incidencias_atm_id"), table_name="incidencias")
    op.drop_table("incidencias")
    op.drop_index(op.f("ix_atm_readings_hora"), table_name="atm_readings")
    op.drop_index(op.f("ix_atm_readings_atm_id"), table_name="atm_readings")
    op.drop_table("atm_readings")
    op.drop_index(op.f("ix_branch_readings_sucursal_id"), table_name="branch_readings")
    op.drop_index(op.f("ix_branch_readings_hora"), table_name="branch_readings")
    op.drop_table("branch_readings")
    op.drop_index(op.f("ix_branch_financials_sucursal_id"), table_name="branch_financials")
    op.drop_index(op.f("ix_branch_financials_fecha"), table_name="branch_financials")
    op.drop_table("branch_financials")
    op.drop_index(op.f("ix_atms_sucursal_id"), table_name="atms")
    op.drop_index(op.f("ix_atms_provincia"), table_name="atms")
    op.drop_index(op.f("ix_atms_estado"), table_name="atms")
    op.drop_index(op.f("ix_atms_codigo_unico"), table_name="atms")
    op.drop_table("atms")
    op.drop_index(op.f("ix_sucursales_provincia"), table_name="sucursales")
    op.drop_table("sucursales")
    op.drop_index(op.f("ix_market_snapshots_provincia"), table_name="market_snapshots")
    op.drop_index(op.f("ix_market_snapshots_institucion_id"), table_name="market_snapshots")
    op.drop_index(op.f("ix_market_snapshots_fecha"), table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_index(op.f("ix_competitor_locations_provincia"), table_name="competitor_locations")
    op.drop_index(op.f("ix_competitor_locations_institucion_id"), table_name="competitor_locations")
    op.drop_table("competitor_locations")
    op.drop_index(op.f("ix_candidate_locations_provincia"), table_name="candidate_locations")
    op.drop_index(
        op.f("ix_candidate_locations_potencial_mercado"), table_name="candidate_locations"
    )
    op.drop_table("candidate_locations")
    op.drop_index(op.f("ix_audit_logs_fecha"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entidad"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_provincias_region"), table_name="provincias")
    op.drop_table("provincias")
    op.drop_index(
        "uq_institutions_own",
        table_name="institutions",
        postgresql_where=sa.text("es_propia = true"),
    )
    op.drop_table("institutions")
    for name in (
        "refill_status",
        "incident_status",
        "severity",
        "atm_status",
        "atm_type",
        "branch_status",
        "location_type",
        "candidate_status",
        "user_role",
    ):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
